# Generated by Django 4.0.1 on 2022-01-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo_proprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor da hora')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor do mês')),
            ],
            options={
                'verbose_name': 'parâmetro',
                'verbose_name_plural': 'parâmetros',
            },
        ),
    ]
