# Generated by Django 4.0.1 on 2022-01-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='movRotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor da hora')),
                ('pago', models.BooleanField(default=False)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'Movimento rotativo',
                'verbose_name_plural': 'Movimentos rotativos',
            },
        ),
    ]
