# Generated by Django 4.0.1 on 2022-01-26 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movrotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='valor por hora'),
        ),
        migrations.AlterField(
            model_name='parametro',
            name='valor_mes',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor mensal'),
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='início')),
                ('valor_mes', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor mensal')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'mensalista',
                'verbose_name_plural': 'mensalistas',
            },
        ),
    ]
