# Generated by Django 4.0.1 on 2022-01-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parametro_valor_hora_alter_parametro_valor_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='movMensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_pgto', models.DateField(verbose_name='data de pagamento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mensalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mensalista')),
            ],
            options={
                'verbose_name': 'movmensalista',
                'verbose_name_plural': 'movmensalistas',
            },
        ),
    ]
