# Generated by Django 4.0.1 on 2022-02-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movmensalista'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movmensalista',
            options={'verbose_name': 'movimento mensal', 'verbose_name_plural': 'movimentos mensais'},
        ),
    ]
