# Generated by Django 4.0.1 on 2022-02-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('endereco', models.CharField(max_length=100, verbose_name='endereço')),
                ('mensagem', models.TextField()),
                ('noticias', models.BooleanField(verbose_name='notícias')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
            },
        ),
    ]
